# Generated by Django 4.0.2 on 2022-10-07 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_city_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='active',
        ),
        migrations.RemoveField(
            model_name='role',
            name='inactive',
        ),
    ]
