# Generated by Django 4.0.2 on 2022-10-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_role_active_remove_role_inactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_monthly',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
