# Generated by Django 4.0.2 on 2022-10-14 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_booking_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='goverment',
        ),
    ]
