# Generated by Django 4.0.2 on 2022-10-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_booking_goverment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='goverment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
