# Generated by Django 4.0.2 on 2022-10-14 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_employer_goverment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='goverment',
        ),
    ]
