# Generated by Django 4.0.2 on 2022-10-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_employer_goverment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='goverment',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
