# Generated by Django 4.0.2 on 2022-10-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_booking_goverment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_id',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
