# Generated by Django 4.1.3 on 2023-02-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_gallary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('attendance', models.BooleanField(default=False)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='gallary',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
