# Generated by Django 4.1.3 on 2023-02-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_attendance_alter_gallary_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallary',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
