# Generated by Django 4.1.3 on 2023-02-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_gallary_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='person_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance',
            field=models.BooleanField(),
        ),
    ]
