# Generated by Django 4.1.7 on 2023-04-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_notification_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='emp_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
