# Generated by Django 4.1.7 on 2023-04-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_notification_emp_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_employed',
            field=models.BooleanField(default=False),
        ),
    ]
