# Generated by Django 4.1.7 on 2023-04-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_notification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True),
        ),
    ]
