# Generated by Django 4.1.7 on 2023-04-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_notification_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
