# Generated by Django 4.1.7 on 2023-04-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='emp_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='emp_city',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
