# Generated by Django 4.1.7 on 2023-04-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_notification_emp_address_notification_emp_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePDFForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=1000)),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=500)),
                ('pdf_file', models.FileField(upload_to='media/Attendance/Attendance_Receipt')),
            ],
        ),
    ]
