# Generated by Django 4.1.7 on 2023-04-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_attendancepdfform'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepdfform',
            name='mem_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='attendancepdfform',
            name='org_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
