# Generated by Django 4.1.7 on 2023-04-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_attendancepdfform_mem_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancepdfform',
            name='mem_name',
        ),
        migrations.AddField(
            model_name='attendancepdfform',
            name='no_of_daye',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
