# Generated by Django 4.1.7 on 2023-04-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_rename_no_of_daye_attendancepdfform_no_of_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancepdfform',
            name='month',
            field=models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=500, null=True),
        ),
    ]
