# Generated by Django 4.1.7 on 2023-04-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_attendancepdfform_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancepdfform',
            name='pdf_file',
            field=models.FileField(upload_to='Attendance/Attendance_Receipt'),
        ),
    ]
