# Generated by Django 4.1.7 on 2023-04-29 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_attendancepdfform_is_uploaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancepdfform',
            name='is_uploaded',
        ),
    ]
