# Generated by Django 4.1.7 on 2023-04-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_remove_attendancepdfform_is_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='month',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
