# Generated by Django 4.1.7 on 2023-04-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_notification_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='month',
        ),
        migrations.AddField(
            model_name='role',
            name='month',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
