# Generated by Django 4.1.7 on 2023-04-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_randomdetails_remove_role_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='RandomDetails',
        ),
    ]
