# Generated by Django 4.1.7 on 2023-05-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_globalsettings_delete_randomdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepdfform',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
