# Generated by Django 4.1.7 on 2023-05-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_attendancepdfform_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='emp_paid',
            field=models.BooleanField(default=False),
        ),
    ]
