# Generated by Django 4.1.7 on 2023-05-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_attendancepdfform_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepdfform',
            name='payment_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
