# Generated by Django 4.1.7 on 2023-05-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_attendancepdfform_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_nam', models.CharField(blank=True, max_length=500, null=True)),
                ('month', models.CharField(blank=True, max_length=500, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=500, null=True)),
                ('is_validated', models.BooleanField(default=False)),
            ],
        ),
    ]
