# Generated by Django 4.1.7 on 2023-05-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_salaryvalidation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salaryvalidation',
            old_name='org_nam',
            new_name='emp_id',
        ),
        migrations.AddField(
            model_name='salaryvalidation',
            name='org_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
