# Generated by Django 4.1.7 on 2023-05-18 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_rename_org_nam_salaryvalidation_emp_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryvalidation',
            name='is_validated',
        ),
    ]
