# Generated by Django 4.1.7 on 2023-05-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_remove_salaryvalidation_is_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryvalidation',
            name='is_validated',
            field=models.BooleanField(blank=True, choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], max_length=500, null=True),
        ),
    ]
