# Generated by Django 4.1.7 on 2023-05-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_salaryvalidation_is_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepdfform',
            name='paid_status',
            field=models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], max_length=500, null=True),
        ),
    ]
