# Generated by Django 4.1.7 on 2023-06-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_course_instructor_name_course_assesment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='goverment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='outer',
            name='goverment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
